#!/bin/bash

source ./includes/helper-functions.inc
source ./includes/fetch-functions.inc
source ./includes/parse-functions.inc
source ./includes/parse-security-rule-functions.inc
source ./includes/parse-sql-server-functions.inc
source ./includes/parse-storage-account-functions.inc
source ./includes/parse-open-source-database-functions.inc
source ./includes/parse-key-vault.inc
source ./includes/parse-cosmosdb.inc
source ./includes/parse-redis.inc
source ./includes/parse-mfa.inc